title: 흑기사 방랑일지
url: 'https://ahden23.github.io'
description: 'ahden의 데브노트'

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Jinho Mang'

#disqus_shortname: lanyonm
#google_analytics: G-NN7JP65RMS

plugins:
  # https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed
